### ISSUE TITLE
Excess info level logging

### ISSUE THREAD

**Issue by FlyingDiver** [HackintoshMan/ShellyMQTT#119]
Every 10 or 20 minutes.  This is not a new device, so I'm not sure why it's being logged at all.

```
Apr 14, 2021 at 11:27:34 AM
   ShellyMQTT                      Updated device details for "Zig-Zag Shelly HT" via announcement message
   ShellyMQTT                      Updated device details for "Zig-Zag Shelly HT" via announcement message

Apr 14, 2021 at 11:37:37 AM
   ShellyMQTT                      Updated device details for "Zig-Zag Shelly HT" via announcement message
   ShellyMQTT                      Updated device details for "Zig-Zag Shelly HT" via announcement message

Apr 14, 2021 at 11:47:31 AM
   ShellyMQTT                      Updated device details for "Zig-Zag Shelly HT" via announcement message
   ShellyMQTT                      Updated device details for "Zig-Zag Shelly HT" via announcement message
```

**Comment by AaronLionsheep** [comment]
Did you recently update the plugin? I had though I surpassed this exact message from being logged previously.

**Comment by FlyingDiver** [comment]
Weird.  Indigo isn't showing an update is available.  But I'm running 0.2.0 and the store says 0.3.0 is available.

**Comment by AaronLionsheep** [comment]
Even weirder is that I have not been able to get the store to recognize my latest updates. 0.7.1 is the latest version I have released on GitHub, and this log message has been changed to be at the debug level (Per #89):
https://github.com/AaronLionsheep/ShellyMQTT/blob/5530112976963eb8cb394c8eefc070edb34eb9eb/ShellyMQTT.indigoPlugin/Contents/Server%20Plugin/Devices/Shelly.py#L345

**Comment by FlyingDiver** [comment]
Send a note to support@indigodomo.com and ask Matt or Jay to check it for you.  They're pretty good about stuff like that.

**Comment by FlyingDiver** [comment]
I'll grab the latest directly from GitHub then.

**Comment by AaronLionsheep** [comment]
Ok thanks. Since you are making the jump from 0.2.0 to 0.7.1, please check the releases thread to make sure you are aware of any breaking changes that have been made.

**Comment by FlyingDiver** [comment]
Will do.

**Comment by AaronLionsheep** [comment]
Specifically, this post should cover it: https://forums.indigodomo.com/viewtopic.php?f=330&t=23697#p200385
