### ISSUE TITLE
Compatibility with future version of Indigo

### ISSUE THREAD

**Issue by paul-e-m** [HackintoshMan/ShellyMQTT#130]
Indigo's plug-in store indicates that this plug-in may not be compatible with versions after Indigo 2022.1.0. All embedded and external Python scripts are now executed in Python 3.10.

Indigo 2022.1 will continue to allow older (Python 2.7) plugins to run, but you will see a warning in the Event Log and they will be marked with a yellow status icon in the Plugins menu indicating that they won't be compatible with future versions of Indigo.

Please see https://www.indigodomo.com/docs/2022.1/getting_started#python_script_changes_and_plugin_compatibility

**Comment by AaronLionsheep** [comment]
@madpsintst Thanks for checking in. Python 3 support will be added, but I cannot provide an ETA.

I'm currently running Indigo 7.4 on a machine that does not support Indigo 2022. I will most likely be performing the upgrade later in the summer depending on hardware releases from Apple.

I will use this issue to track progress on the Python 3 upgrade.

**Comment by paul-e-m** [comment]
Terrific! And thanks for making this plugin available. It sure simplifies MQTT control of my Shelly devices. Indigo combined with an MQTT broker and node-red makes for a formidable smart home control solution.

**Comment by AaronLionsheep** [comment]
I am now running on Indigo 2022.1, so I can begin the Python3 conversion process. I will fix the remaining bugs that have been identified before this process so anyone still running Indigo pre-2022 can have a decent experience.

**Comment by AaronLionsheep** [comment]
I am currently running my system on [this](https://github.com/AaronLionsheep/ShellyMQTT/tree/python3) branch which has Python3 support.
