### ISSUE TITLE
Extraneous logging

### ISSUE THREAD

**Issue by FlyingDiver** [HackintoshMan/ShellyMQTT#89]
This line probably ought to be Debug level, as there's no information useful to the end user:

`   ShellyMQTT                      Updated device details for "Barn Shelly HT" via announcement message
`

**Comment by AaronLionsheep** [comment]
https://github.com/AaronLionsheep/ShellyMQTT/blob/0364e35828ec21eb64292edd299b34df32fef9f5/ShellyMQTT.indigoPlugin/Contents/Server%20Plugin/Devices/Shelly.py#L322

Thanks, I will look into adjusting the logging level as this does appear to be more diagnostic-focused.

**Comment by FlyingDiver** [comment]
Probably most of the logging in that file should be debug level. Like logging on/off commands to a device.

**Comment by AaronLionsheep** [comment]
Yes I see:
https://github.com/AaronLionsheep/ShellyMQTT/blob/0364e35828ec21eb64292edd299b34df32fef9f5/ShellyMQTT.indigoPlugin/Contents/Server%20Plugin/Devices/Shelly.py#L409
which is really debug information.

As for commanding a device on/off, I followed the Insteon device pattern with logging commands. I should probably allow the user to select a logging level higher than info.

**Comment by FlyingDiver** [comment]
Should this be closed now?

**Comment by AaronLionsheep** [comment]
Have you tried the 0.2.4 branch where this code is sitting? I typically keep changes in their own branch until I have run that version of the plugin for a bit. When I merge those changes into the master branch is when I close out the issues.

I was planning to wrap up 0.2.4 this weekend.

**Comment by FlyingDiver** [comment]
OK, no problem.  Was trying to clean up all the issues in GitHub, and I saw this one was still open.
